services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres-db-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: always
    networks:
      - postgres-db-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 16543:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres-db-network

  siweapp-backend:
    container_name: siweapp_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - postgres-db-network
    depends_on:
      - postgres
      - pgadmin

volumes:
  postgres-db-volume:
    driver: local

networks:
  postgres-db-network:
    driver: bridge
